CREATE TABLE users(
    id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    username VARCHAR(255) NOT NULL,
    password CHAR(60) NOT NULL,
    role VARCHAR(20) NOT NULL,
    wins INTEGER NOT NULL DEFAULT 0,
    UNIQUE (username)
)